# Generated by Django 5.2.6 on 2026-09-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012 -- Django migration declaration
        ("docai", "0001_initial"),
    ]

    operations = [  # noqa: RUF012 -- Django migration declaration
        migrations.AddField(
            model_name="runitem",
            name="worker_deliveries",
            field=models.PositiveSmallIntegerField(
                db_comment="Deliveries for current task",
                default=0,
                help_text="Delivery count for the current Celery task id.",
            ),
        ),
        migrations.AddField(
            model_name="runitem",
            name="worker_task_id",
            field=models.CharField(
                blank=True,
                db_comment="Current worker delivery",
                help_text="Celery task id currently responsible for this item.",
                max_length=64,
            ),
        ),
    ]
