# Generated by Django 5.2.17 on 2026-09-12 04:08

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("docai", "0004_backfill_runitem_audit_users"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMUsageEvent",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        db_comment="Workflow stage",
                        help_text="Workflow stage, such as classification or extraction.",
                        max_length=32,
                    ),
                ),
                (
                    "chunk_index",
                    models.PositiveIntegerField(
                        blank=True,
                        db_comment="Chunk index",
                        help_text="Zero-based chunk index when the call processed a chunk.",
                        null=True,
                    ),
                ),
                (
                    "segment_index",
                    models.PositiveIntegerField(
                        blank=True,
                        db_comment="Segment index",
                        help_text="Zero-based segment index when the call processed a segment.",
                        null=True,
                    ),
                ),
                (
                    "attempt",
                    models.PositiveSmallIntegerField(
                        db_comment="Item attempt",
                        default=1,
                        help_text="Run-item attempt during which the provider responded.",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        db_comment="Provider adapter",
                        help_text="Provider adapter that reported usage.",
                        max_length=32,
                    ),
                ),
                (
                    "model_deployment",
                    models.CharField(
                        blank=True,
                        db_comment="Model deployment",
                        help_text="Configured model deployment.",
                        max_length=120,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        blank=True,
                        db_comment="Provider model",
                        help_text="Model identifier reported by the provider.",
                        max_length=120,
                    ),
                ),
                (
                    "provider_request_id",
                    models.CharField(
                        blank=True,
                        db_comment="Provider request id",
                        help_text="Provider response identifier for reconciliation.",
                        max_length=128,
                    ),
                ),
                (
                    "prompt_name",
                    models.CharField(
                        blank=True,
                        db_comment="Prompt name",
                        help_text="Prompt name.",
                        max_length=120,
                    ),
                ),
                (
                    "prompt_version",
                    models.PositiveIntegerField(
                        blank=True,
                        db_comment="Prompt version",
                        help_text="Prompt version.",
                        null=True,
                    ),
                ),
                (
                    "schema_name",
                    models.CharField(
                        blank=True,
                        db_comment="Schema name",
                        help_text="Output schema name.",
                        max_length=120,
                    ),
                ),
                (
                    "schema_version",
                    models.PositiveIntegerField(
                        blank=True,
                        db_comment="Schema version",
                        help_text="Output schema version.",
                        null=True,
                    ),
                ),
                (
                    "input_tokens",
                    models.PositiveBigIntegerField(
                        blank=True,
                        db_comment="Input tokens",
                        help_text="Input tokens reported by the provider.",
                        null=True,
                    ),
                ),
                (
                    "cached_input_tokens",
                    models.PositiveBigIntegerField(
                        db_comment="Cached input tokens",
                        default=0,
                        help_text="Cached input tokens included in input_tokens.",
                    ),
                ),
                (
                    "output_tokens",
                    models.PositiveBigIntegerField(
                        blank=True,
                        db_comment="Output tokens",
                        help_text="Output tokens reported by the provider.",
                        null=True,
                    ),
                ),
                (
                    "reasoning_tokens",
                    models.PositiveBigIntegerField(
                        db_comment="Reasoning tokens",
                        default=0,
                        help_text="Reasoning tokens included in output_tokens.",
                    ),
                ),
                (
                    "total_tokens",
                    models.PositiveBigIntegerField(
                        blank=True,
                        db_comment="Total tokens",
                        help_text="Total tokens reported by the provider.",
                        null=True,
                    ),
                ),
                (
                    "latency_ms",
                    models.PositiveIntegerField(
                        db_comment="Provider latency",
                        default=0,
                        help_text="End-to-end adapter latency in milliseconds.",
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[("succeeded", "Succeeded"), ("invalid_output", "Invalid output")],
                        db_comment="Call outcome",
                        default="succeeded",
                        help_text="Whether structured output validation succeeded.",
                        max_length=24,
                    ),
                ),
                (
                    "token_details",
                    models.JSONField(
                        blank=True,
                        db_comment="Provider token details",
                        default=dict,
                        help_text="Non-content token details reported by the provider.",
                    ),
                ),
                (
                    "correlation_id",
                    models.CharField(
                        blank=True,
                        db_comment="Trace id",
                        help_text="Correlation id.",
                        max_length=32,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created the record",
                        help_text="User who created this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        db_comment="Document",
                        help_text="Document processed by this model call.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llm_usage_events",
                        to="docai.document",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        db_comment="Run",
                        help_text="Run that caused this model call.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llm_usage_events",
                        to="docai.run",
                    ),
                ),
                (
                    "run_item",
                    models.ForeignKey(
                        db_comment="Run item",
                        help_text="Per-document job that caused this model call.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llm_usage_events",
                        to="docai.runitem",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who last updated the record",
                        help_text="User who last updated this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "LLM usage event",
                "verbose_name_plural": "LLM usage events",
                "db_table": "docai_llm_usage_event",
                "db_table_comment": "Per-provider-response token usage without prompt or document content",
                "ordering": ["-created"],
                "indexes": [
                    models.Index(fields=["run", "created"], name="ix_docai_llmu_run_created"),
                    models.Index(fields=["run_item"], name="ix_docai_llmu_item"),
                    models.Index(fields=["run", "stage"], name="ix_docai_llmu_run_stage"),
                ],
            },
        ),
    ]
