# Generated by Django 5.2.17 on 2026-09-12 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("docai", "0005_llmusageevent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="llmusageevent",
            name="document",
        ),
        migrations.RemoveField(
            model_name="llmusageevent",
            name="modified",
        ),
        migrations.RemoveField(
            model_name="llmusageevent",
            name="token_details",
        ),
        migrations.RemoveField(
            model_name="llmusageevent",
            name="updated_by",
        ),
        migrations.AddField(
            model_name="llmusageevent",
            name="api_version",
            field=models.CharField(
                blank=True,
                db_comment="Provider API version",
                help_text="Configured provider API version used for the call.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="llmusageevent",
            name="finish_reason",
            field=models.CharField(
                blank=True,
                db_comment="Provider finish reason",
                help_text="Provider-reported reason the response ended.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="llmusageevent",
            name="safety_outcome",
            field=models.CharField(
                choices=[
                    ("unknown", "Not reported"),
                    ("clear", "Clear"),
                    ("flagged", "Flagged"),
                    ("blocked", "Blocked"),
                ],
                db_comment="Normalized safety outcome",
                default="unknown",
                help_text="Content-free summary of provider safety signals.",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="llmusageevent",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                db_comment="Recorded at",
                help_text="When this immutable event was recorded.",
            ),
        ),
        migrations.AlterField(
            model_name="llmusageevent",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_comment="Initiating user",
                help_text="User whose run caused this event.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
