# Generated by Django 5.2.17 on 2026-09-13 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Q


def backfill_run_layouts(apps, schema_editor):
    """Only attach evidence-supported layouts; never guess among historical versions."""
    alias = schema_editor.connection.alias
    Artifact = apps.get_model("docai", "ProcessingArtifact")
    Item = apps.get_model("docai", "RunItem")
    Span = apps.get_model("docai", "SourceSpan")
    for item in Item.objects.using(alias).all().iterator(chunk_size=500):
        evidence = set(
            Span.objects.using(alias)
            .filter(
                Q(field__run_id=item.run_id, field__document_id=item.document_id)
                | Q(
                    classification__run_id=item.run_id, classification__document_id=item.document_id
                )
                | Q(segment__run_id=item.run_id, segment__document_id=item.document_id),
                unit__layout_artifact__isnull=False,
            )
            .values_list("unit__layout_artifact_id", flat=True)
        )
        if len(evidence) == 1:
            artifact_id = evidence.pop()
        elif not evidence and (
            item.status == "succeeded"
            or (item.status == "failed" and item.stage in {"workflow", "persist"})
        ):
            candidates = list(
                Artifact.objects.using(alias)
                .filter(
                    document_id=item.document_id,
                    kind="layout",
                    created__lte=item.modified,
                )
                .values_list("pk", flat=True)[:2]
            )
            artifact_id = candidates[0] if len(candidates) == 1 else None
        else:
            artifact_id = None
        if artifact_id is not None:
            Item.objects.using(alias).filter(pk=item.pk).update(layout_artifact_id=artifact_id)


class Migration(migrations.Migration):
    dependencies = [
        ("docai", "0006_remove_llmusageevent_document_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="sourceunit",
            name="uq_docai_unit_doc_idx",
        ),
        migrations.AddField(
            model_name="processingartifact",
            name="cache_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Scalar hash of source and processing policy; blank artifacts are not reusable.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="processingartifact",
            name="source_artifact",
            field=models.ForeignKey(
                blank=True,
                help_text="Exact derived input analyzed for this layout.",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="derived_layouts",
                to="docai.processingartifact",
            ),
        ),
        migrations.AddField(
            model_name="runitem",
            name="input_quality",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Scan enhancement summary and recoverable warnings.",
            ),
        ),
        migrations.AddField(
            model_name="runitem",
            name="layout_artifact",
            field=models.ForeignKey(
                blank=True,
                help_text="Immutable layout used by this exact execution.",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="run_items",
                to="docai.processingartifact",
            ),
        ),
        migrations.AlterField(
            model_name="sourceunit",
            name="layout_artifact",
            field=models.ForeignKey(
                blank=True,
                db_comment="Normalized layout artifact",
                help_text="Artifact holding this unit's normalized layout.",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="units",
                to="docai.processingartifact",
            ),
        ),
        migrations.AddIndex(
            model_name="processingartifact",
            index=models.Index(fields=["document", "kind", "cache_key"], name="ix_docai_art_cache"),
        ),
        migrations.RunPython(backfill_run_layouts, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="sourceunit",
            constraint=models.UniqueConstraint(
                fields=("document", "layout_artifact", "kind", "index"),
                name="uq_docai_unit_layout_idx",
            ),
        ),
    ]
