# Generated by Django 5.2.17 on 2026-09-13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("docai", "0007_version_processing_layouts")]

    operations = [
        migrations.AddField(
            model_name="runitem",
            name="processing_progress",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Latest bounded processing milestone; empty for historical runs.",
            ),
        ),
        migrations.AddField(
            model_name="runitem",
            name="progress_updated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the latest processing milestone was recorded.",
                null=True,
            ),
        ),
    ]
