# Generated by Django 5.2.17 on 2026-09-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("docai", "0008_runitem_processing_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="extractedfield",
            name="list_candidates",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Conflicting list candidates with source references; retained for human review.",
            ),
        ),
    ]
