# Generated by Django 5.2.17 on 2026-09-15 16:35

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("docai", "0009_list_field_candidates"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowInvocation",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "key",
                    models.CharField(help_text="Caller-supplied Idempotency-Key.", max_length=128),
                ),
                (
                    "request_hash",
                    models.CharField(
                        help_text="SHA-256 of the canonical request identity.", max_length=64
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("accepting", "Accepting request"),
                            ("run_created", "Run created"),
                            ("failed", "Failed before run creation"),
                        ],
                        default="accepting",
                        help_text="Reservation state before a run is available.",
                        max_length=16,
                    ),
                ),
                ("failure_status", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("failure_code", models.CharField(blank=True, max_length=64)),
                ("failure_message", models.CharField(blank=True, max_length=500)),
                (
                    "failure_errors",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Bounded validation details replayed to an identical retry.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created the record",
                        help_text="User who created this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        help_text="Dataset supplied with the invocation.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workflow_invocations",
                        to="docai.dataset",
                    ),
                ),
                (
                    "run",
                    models.OneToOneField(
                        blank=True,
                        help_text="Run created by this invocation, when available.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invocation",
                        to="docai.run",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who last updated the record",
                        help_text="User who last updated this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        help_text="Pinned workflow version requested by the caller.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invocations",
                        to="docai.workflowconfiguration",
                    ),
                ),
            ],
            options={
                "db_table": "docai_workflow_invocation",
                "ordering": ["-created"],
                "indexes": [
                    models.Index(fields=["workflow", "created"], name="ix_inv_wf_created"),
                    models.Index(fields=["request_hash"], name="ix_inv_request_hash"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("created_by", "workflow", "key"), name="uq_inv_user_wf_key"
                    )
                ],
            },
        ),
    ]
