# Generated by Django 5.2.17 on 2026-09-15 17:48

import docai.models.results
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("docai", "0010_workflowinvocation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="client_reference",
            field=models.CharField(
                blank=True,
                db_comment="Caller correlation reference",
                help_text="Optional caller-owned reference for operational reconciliation.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="workflowinvocation",
            name="expires_at",
            field=models.DateTimeField(
                default=docai.models.results.invocation_expiry,
                help_text="End of the persisted idempotency replay guarantee.",
            ),
        ),
        migrations.AddIndex(
            model_name="run",
            index=models.Index(fields=["client_reference"], name="ix_docai_run_client_ref"),
        ),
        migrations.AddIndex(
            model_name="workflowinvocation",
            index=models.Index(fields=["expires_at"], name="ix_inv_expires"),
        ),
    ]
