# Generated by Django 5.2.17 on 2026-09-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("docai", "0011_run_client_reference_workflowinvocation_expires_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowinvocation",
            name="lease_expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Short acceptance or dispatch ownership lease; not the replay expiry.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="workflowinvocation",
            name="lease_token",
            field=models.CharField(
                blank=True,
                help_text="Opaque owner token preventing a stale request from committing after takeover.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="workflowinvocation",
            name="status",
            field=models.CharField(
                choices=[
                    ("accepting", "Accepting request"),
                    ("dispatching", "Dispatching run"),
                    ("accepted", "Run accepted"),
                    ("failed", "Failed before run creation"),
                ],
                default="accepting",
                help_text="Acceptance, dispatch, or replay state for this invocation.",
                max_length=16,
            ),
        ),
    ]
