# Generated by Django 5.2.17 on 2026-09-17 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("docai", "0014_sourceunit_layout_storage_path"),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="processingcheckpoint",
            table_comment="Private per-run-item checkpoints for provider recovery and validated output reuse",
        ),
        migrations.AlterField(
            model_name="processingcheckpoint",
            name="artifact",
            field=models.ForeignKey(
                db_comment="Private validated-output artifact",
                help_text="Stored LLM result used for replay; absent for Document Intelligence operation checkpoints.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checkpoints",
                to="docai.processingartifact",
            ),
        ),
        migrations.AlterField(
            model_name="processingcheckpoint",
            name="fingerprint",
            field=models.CharField(
                db_comment="SHA-256 of effective processing inputs",
                help_text="Identifies compatible inputs and configuration; unique per run item and checkpoint type.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="processingcheckpoint",
            name="kind",
            field=models.CharField(
                db_comment="di_operation|llm_output",
                help_text="Checkpoint type: a resumable Document Intelligence operation or validated LLM output.",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="processingcheckpoint",
            name="metadata",
            field=models.JSONField(
                db_comment="Private provider-operation recovery state",
                default=dict,
                help_text="Saved operation reference and resubmission state; empty for LLM-output checkpoints.",
            ),
        ),
        migrations.AlterField(
            model_name="processingcheckpoint",
            name="run_item",
            field=models.ForeignKey(
                db_comment="Owning run item",
                help_text="Document-processing item whose attempts may reuse this checkpoint.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checkpoints",
                to="docai.runitem",
            ),
        ),
    ]
