# Generated by Django 5.2.17 on 2026-09-29 00:26

import django.db.models.deletion
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("docai", "0015_document_processing_checkpoint_metadata"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaygroundSession",
            fields=[
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Recorded at",
                        help_text="When this immutable event was recorded.",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        db_comment="Expiry instant",
                        db_index=True,
                        help_text="Session and temporary samples are removed after this instant.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        db_comment="Generation state",
                        default="ready",
                        help_text="Ready, queued, analyzing, generating, complete, or failed.",
                        max_length=20,
                    ),
                ),
                (
                    "state_changed_at",
                    models.DateTimeField(
                        db_comment="Last generation-stage change",
                        help_text="Used to detect a worker that stopped before recording a terminal state.",
                        null=True,
                    ),
                ),
                (
                    "goal",
                    models.TextField(
                        blank=True,
                        db_comment="Operator's requested outcome",
                        help_text="Short workflow goal; do not put document contents here.",
                    ),
                ),
                (
                    "workflow_type",
                    models.CharField(
                        blank=True,
                        db_comment="Proposed workflow type",
                        help_text="One of the three supported playground workflow types.",
                        max_length=40,
                    ),
                ),
                (
                    "proposal",
                    models.JSONField(
                        db_comment="Editable proposal metadata",
                        default=dict,
                        help_text="Fields and source labels without sample values.",
                    ),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True,
                        db_comment="Failure category",
                        help_text="Stable machine-readable generation failure code.",
                        max_length=40,
                    ),
                ),
                (
                    "error_message",
                    models.CharField(
                        blank=True,
                        db_comment="Safe failure explanation",
                        help_text="Operator-facing error without source content.",
                        max_length=500,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Initiating user",
                        help_text="User whose run caused this event.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        db_comment="Owning project",
                        help_text="Project used for document access.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="docai.project",
                    ),
                ),
            ],
            options={
                "db_table": "docai_playground_session",
                "db_table_comment": "Temporary guided workflow proposal owned by one operator",
            },
        ),
        migrations.CreateModel(
            name="PlaygroundSample",
            fields=[
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Recorded at",
                        help_text="When this immutable event was recorded.",
                    ),
                ),
                (
                    "storage_path",
                    models.CharField(
                        blank=True,
                        db_comment="Temporary source path",
                        help_text="Private application storage path for a new upload.",
                        max_length=255,
                    ),
                ),
                (
                    "filename",
                    models.CharField(
                        db_comment="Display filename",
                        help_text="Original filename for the sample.",
                        max_length=255,
                    ),
                ),
                (
                    "file_format",
                    models.CharField(
                        db_comment="Detected format",
                        help_text="Normalized source format.",
                        max_length=8,
                    ),
                ),
                (
                    "size_bytes",
                    models.BigIntegerField(
                        db_comment="Source byte count",
                        help_text="Used to enforce total sample limits.",
                    ),
                ),
                (
                    "unit_count",
                    models.PositiveIntegerField(
                        db_comment="Pages or sheets",
                        help_text="Expected pages or sheets for completeness checks.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Initiating user",
                        help_text="User whose run caused this event.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Existing dataset document",
                        help_text="Reference to an existing document; no copy is made.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="docai.document",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        db_comment="Playground session",
                        help_text="Session using this sample.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="samples",
                        to="docai.playgroundsession",
                    ),
                ),
            ],
            options={
                "db_table": "docai_playground_sample",
                "db_table_comment": "Temporary upload or reference to an existing dataset document",
            },
        ),
        migrations.CreateModel(
            name="PlaygroundUsageEvent",
            fields=[
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Recorded at",
                        help_text="When this immutable event was recorded.",
                    ),
                ),
                (
                    "project_id_snapshot",
                    models.UUIDField(
                        db_comment="Project at call time",
                        help_text="Keeps project-level usage attributable after the short-lived session expires.",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        db_comment="Call stage", help_text="Generate or refine.", max_length=24
                    ),
                ),
                (
                    "deployment",
                    models.CharField(
                        blank=True,
                        db_comment="Model deployment",
                        help_text="Deployment used for the call.",
                        max_length=120,
                    ),
                ),
                (
                    "input_tokens",
                    models.PositiveIntegerField(
                        db_comment="Input tokens",
                        help_text="Provider-reported input tokens.",
                        null=True,
                    ),
                ),
                (
                    "cached_input_tokens",
                    models.PositiveIntegerField(
                        db_comment="Cached input tokens",
                        default=0,
                        help_text="Provider-reported cache-read tokens.",
                    ),
                ),
                (
                    "output_tokens",
                    models.PositiveIntegerField(
                        db_comment="Output tokens",
                        help_text="Provider-reported output tokens.",
                        null=True,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        db_comment="Call outcome",
                        help_text="Provider-reported outcome.",
                        max_length=24,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Initiating user",
                        help_text="User whose run caused this event.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        db_comment="Playground session",
                        help_text="Session making this model call, if it has not expired or been deleted.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_events",
                        to="docai.playgroundsession",
                    ),
                ),
            ],
            options={
                "db_table": "docai_playground_usage",
                "db_table_comment": "Content-free token usage for playground model calls",
            },
        ),
        migrations.AddIndex(
            model_name="playgroundsession",
            index=models.Index(fields=["created_by", "expires_at"], name="ix_pg_owner_expiry"),
        ),
        migrations.AddIndex(
            model_name="playgroundsample",
            index=models.Index(fields=["session"], name="ix_pg_sample_session"),
        ),
        migrations.AddIndex(
            model_name="playgroundusageevent",
            index=models.Index(fields=["session", "created"], name="ix_pg_usage_session"),
        ),
    ]
