# Generated by Django 5.2.17 on 2026-09-29 01:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("docai", "0016_playgroundsession_playgroundsample_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="playgroundsession",
            name="last_activity_at",
            field=models.DateTimeField(
                db_comment="Last playground activity",
                db_index=True,
                default=django.utils.timezone.now,
                help_text="Most recent sample, proposal, or generation-stage change for resume ordering.",
            ),
        ),
    ]
