# Generated by Django 5.2.17 on 2026-09-29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("docai", "0017_playgroundsession_last_activity_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="playgroundsession",
            name="generation_attempt",
            field=models.UUIDField(
                db_comment="Current generation attempt",
                editable=False,
                help_text=(
                    "Fences delayed workers so only the current generation attempt can update "
                    "this session."
                ),
                null=True,
            ),
        ),
    ]
